// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

namespace GameGeek.Character
{
	public enum PatrolStatus
	{
		IDLE = 0,
		WANDER = 1,
		WARN = 2,
		CHASE = 3,
		BATTLE = 3,
		RETURN = 4,
	}
}
