// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

namespace GameGeek.Character
{
	public enum SkillType
	{
		CT_NULL = 1,
		CT_MAGIC = 0,
		CT_PHYSICAL = 1,
	}
}
