// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

namespace GameGeek.Character
{
	public enum SkillStatus
	{
		SS_CAN_CAST = 0,
		SS_NOT_ENOUGH_MP = 1,
		SS_IN_CD = 2,
		SS_IN_RELEASING = 3,
		SS_NO_ENEMY = 4,
	}
}
