// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace GameGeek.Character
{
	public class PlayerCharacterProperty : CharacterProperty
	{
		public int experience;
		public GameGeek.Character.GenderType gender;
	}
}
