// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

namespace GameGeek.Character
{
	public enum AppearStatus
	{
		AS_NULL = 0,
		AS_IDLE = 1,
		AS_MOVE = 2,
		AS_ATTACK = 3,
		AS_SKILL = 4,
		AS_DEFENSE = 5,
		AS_KNOCKING_UP = 6,
		AS_DIE = 7,
	}
}
