// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

namespace GameGeek.Character
{
    ///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT
    [UnityEngine.RequireComponent(typeof(CharacterProperty))]
    ///<<< END WRITING YOUR CODE

    public class Character : behaviac.Agent
    ///<<< BEGIN WRITING YOUR CODE Character
    ///<<< END WRITING YOUR CODE
    {
        public GameGeek.Character.CharacterType characterType = GameGeek.Character.CharacterType.CT_NULL;

        public GameGeek.Character.CharacterProperty property = null;

        ///<<< BEGIN WRITING YOUR CODE CLASS_PART

        void Awake()
        {
            BehaviacInitializer.InitBehavic();
        }
		
		public behaviac.EBTStatus _status = behaviac.EBTStatus.BT_INVALID;

        void FixedUpdate()
        {
            if (_status == behaviac.EBTStatus.BT_RUNNING)
            {
                _status = this.btexec();
            }
        }
        ///<<< END WRITING YOUR CODE

    }

    ///<<< BEGIN WRITING YOUR CODE NAMESPACE_UNINIT

    ///<<< END WRITING YOUR CODE
}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

