// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

namespace GameGeek.Character
{
	public enum GenderType
	{
		UNKNOW = 0,
		GT_FEMALE = 0,
		GT_MALE = 1,
	}
}
