// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../Assets/Scripts/behaviac/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: PlayerBehaviorsTree

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_PlayerBehaviorsTree_node0 : behaviac.Action
	{
		public Action_bt_PlayerBehaviorsTree_node0()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((PlayerAgent)pAgent).Move();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_PlayerBehaviorsTree
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("PlayerBehaviorsTree");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("PlayerAgent");
#endif
			// children
			{
				Action_bt_PlayerBehaviorsTree_node0 node0 = new Action_bt_PlayerBehaviorsTree_node0();
				node0.SetClassNameString("Action");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("PlayerAgent");
#endif
				bt.AddChild(node0);
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: PlayerStateMachine

	[behaviac.GeneratedTypeMetaInfo()]
	class State_bt_PlayerStateMachine_node1 : behaviac.State
	{
		public State_bt_PlayerStateMachine_node1()
		{
			this.m_bIsEndState = false;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			return behaviac.EBTStatus.BT_RUNNING;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Transition_bt_PlayerStateMachine_attach4 : behaviac.Transition
	{
		public Transition_bt_PlayerStateMachine_attach4()
		{
			this.TargetStateId = 2;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			bool opl = (bool)AgentMetaVisitor.GetProperty(pAgent, "isMoving");
			bool opr2 = true;
			bool op = (opl == opr2);
			if (!op)
				result = EBTStatus.BT_FAILURE;
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Transition_bt_PlayerStateMachine_attach7 : behaviac.Transition
	{
		public Transition_bt_PlayerStateMachine_attach7()
		{
			this.TargetStateId = 3;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			float opl = (float)AgentMetaVisitor.GetProperty(pAgent, "distanceToEnemy");
			float opr2 = 0.1f;
			bool op = (opl <= opr2);
			if (!op)
				result = EBTStatus.BT_FAILURE;
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class State_bt_PlayerStateMachine_node2 : behaviac.State
	{
		public State_bt_PlayerStateMachine_node2()
		{
			this.m_bIsEndState = false;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			return behaviac.EBTStatus.BT_RUNNING;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Transition_bt_PlayerStateMachine_attach5 : behaviac.Transition
	{
		public Transition_bt_PlayerStateMachine_attach5()
		{
			this.TargetStateId = 1;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			bool opl = (bool)AgentMetaVisitor.GetProperty(pAgent, "isMoving");
			bool opr2 = false;
			bool op = (opl == opr2);
			if (!op)
				result = EBTStatus.BT_FAILURE;
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class State_bt_PlayerStateMachine_node3 : behaviac.State
	{
		public State_bt_PlayerStateMachine_node3()
		{
			this.m_bIsEndState = false;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			return behaviac.EBTStatus.BT_RUNNING;
		}
	}

	public static class bt_PlayerStateMachine
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("PlayerStateMachine");
			bt.IsFSM = true;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("PlayerAgent");
#endif
			// attachments
			// children
			{
				FSM fsm = new FSM();
				fsm.SetClassNameString("FSM");
				fsm.SetId(-1);
				fsm.InitialId = 1;
#if !BEHAVIAC_RELEASE
				fsm.SetAgentType("PlayerAgent");
#endif
				{
					State_bt_PlayerStateMachine_node1 node1 = new State_bt_PlayerStateMachine_node1();
					node1.SetClassNameString("State");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("PlayerAgent");
#endif
					// attachments
					{
						Transition_bt_PlayerStateMachine_attach4 attach4 = new Transition_bt_PlayerStateMachine_attach4();
						attach4.SetClassNameString("Transition");
						attach4.SetId(4);
#if !BEHAVIAC_RELEASE
						attach4.SetAgentType("PlayerAgent");
#endif
						node1.Attach(attach4, false, false, true);
					}
					{
						Transition_bt_PlayerStateMachine_attach7 attach7 = new Transition_bt_PlayerStateMachine_attach7();
						attach7.SetClassNameString("Transition");
						attach7.SetId(7);
#if !BEHAVIAC_RELEASE
						attach7.SetAgentType("PlayerAgent");
#endif
						node1.Attach(attach7, false, false, true);
					}
					fsm.AddChild(node1);
					fsm.SetHasEvents(fsm.HasEvents() | node1.HasEvents());
				}
				{
					State_bt_PlayerStateMachine_node2 node2 = new State_bt_PlayerStateMachine_node2();
					node2.SetClassNameString("State");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("PlayerAgent");
#endif
					// attachments
					{
						Transition_bt_PlayerStateMachine_attach5 attach5 = new Transition_bt_PlayerStateMachine_attach5();
						attach5.SetClassNameString("Transition");
						attach5.SetId(5);
#if !BEHAVIAC_RELEASE
						attach5.SetAgentType("PlayerAgent");
#endif
						node2.Attach(attach5, false, false, true);
					}
					fsm.AddChild(node2);
					fsm.SetHasEvents(fsm.HasEvents() | node2.HasEvents());
				}
				{
					State_bt_PlayerStateMachine_node3 node3 = new State_bt_PlayerStateMachine_node3();
					node3.SetClassNameString("State");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("PlayerAgent");
#endif
					fsm.AddChild(node3);
					fsm.SetHasEvents(fsm.HasEvents() | node3.HasEvents());
				}
				bt.AddChild(fsm);
			}
			return true;
		}
	}

}
